### ISSUE TITLE
Question: is there any relationship to CppSharp?

### ISSUE THREAD

**Issue by lostmsu** [microsoft/ClangSharp#119]
I am trying to understand which one I should be looking into.

https://github.com/mono/CppSharp

**Comment by tannergooding** [comment]
They are oriented towards different scenarios. ClangSharp aims to provide a minimal wrapper over Clang and to provide a basic P/Invoke generation tool that handles C like (and minimal C++ like) header files.
The bindings it generates are very low level and have essentially zero overhead.

CppSharp also provides a wrapper over Clang and provides P/Invoke generation functionality, but it is more oriented towards full C++ and generates stuff that just works, but which may have higher level abstractions that introduce overhead.
