### ISSUE TITLE
Clang 10.0.0 support?

### ISSUE THREAD

**Issue by mugisoba** [microsoft/ClangSharp#120]
Clang 10.0.0 has been released, do you have any plans to support it?

https://releases.llvm.org/10.0.0/tools/clang/docs/ReleaseNotes.html

**Comment by tannergooding** [comment]
Yes. I was just waiting on more pre-built binaries to get up (as its simpler to take those over building local copies): https://releases.llvm.org/download.html#10.0.0

The following are currently up, so the process can probably start soon:
```
macOS
FreeBSD11 AMD64
FreeBSD11 i386
AArch64 Linux
armv7a Linux
SuSE Linux Enterprise Server 11SP3 x86_64
Ubuntu 18.04
PowerPC64LE Red Hat Enterprise Linux 7.4
PowerPC64LE Ubuntu 16.04
Solaris 11.4 AMD64
Solaris 11.4 SPARCv9
Windows (32-bit)
Windows (64-bit)
```

The following that were in the previous release (https://releases.llvm.org/download.html#9.0.0) are not:
```
Ubuntu 14.04
Ubuntu 16.04
Ubuntu 19.04
```

I imagine 14.04 and 19.04 won't be coming. 14.04 is out of regular support and was dropped from https://apt.llvm.org/ and I believe 19.04 is fully EOL now.
They did publish binaries for 16.04 for PowerPC, so I'd guess they are planning on doing the same for regular `x64` as well (and `20.04` will be coming near the end of the month)...

**Comment by mugisoba** [comment]
Thank you for your quick reply.
I'm looking forward to that 👍

**Comment by tannergooding** [comment]
The initial packages are up for `libClang`. I'll work on getting packages up for `ClangSharp` itself this weekend.

**Comment by tannergooding** [comment]
The intial packaes for `ClangSharp` were uploaded a number of days ago, just forgot to update and resolve the issue.
