### ISSUE TITLE
Dll not found if RID is not specified

### ISSUE THREAD

**Issue by xoofx** [microsoft/ClangSharp#129]
Hello!
For [CppAst](https://github.com/xoofx/CppAst/) I was previously using my own [libclang package](https://github.com/xoofx/libclang) mainly because ClangSharp was not providing an updated NuGet package.  

Now I have switched CppAst to use the beta ClangSharp 10.0 package, but my tests failed to work as I had to run them explicitly with a RID, e.g `dotnet tests -c Release -platform win-x64` while with my package I didn't have to specify anything. 
But It is a bit annoying for a end-user experience to have to specify this RID...

Do you know why this is not working with the libclang package that you ship?

**Comment by tannergooding** [comment]
This is essentially a dup of https://github.com/microsoft/ClangSharp/issues/118.

There is a limitation on the size of NuGet packages that nuget.org allows (250MB iirc) and it is undesirable for users to download hundreds of megabytes when they only need the binaries for their host box. So, the root package currently contains a `runtime.json` that lists the RID specific packages which should be downloaded instead.

There seems to be an issue preventing native assets from being resolved using this mechanism and that is pending a resolution. The simplest workaround today is to add `<RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND '$(PackAsTool)' != 'true'">$(NETCoreSdkRuntimeIdentifier)</RuntimeIdentifier>` which will use the RID of the .NET SDK and should allow things to work in a dev environment.

**Comment by xoofx** [comment]
Han, right, it's unfortunate, but the workaround is working fine, I will use that, thanks!
