### ISSUE TITLE
Make --libraryPath CLI option optional

### ISSUE THREAD

**Issue by nathan-alden-sr** [microsoft/ClangSharp#131]
Oftentimes there are headers that do not contain function declarations. In these cases, there is no library path to supply to ClangSharp; however, ClangSharp currently treats this parameter as required. It would be nice if the parameter was optional and only generated an error if a function declaration was encountered.

**Comment by tannergooding** [comment]
Marked this as help wanted as it is a fairly trivial change. Will try to get to it soon if it isn't picked up.
