### ISSUE TITLE
Add --include CLI option

### ISSUE THREAD

**Issue by nathan-alden-sr** [microsoft/ClangSharp#132]
When processing large headers like `winnt.h`, it is often desirable to only generate a few bindings at a time. This helps to keep PRs smaller and focused. I'd love a `--include` option to mirror what `--exclude` does: if `--include` is specified then essentially all symbols _not_ in the include list should be excluded.

**Comment by tannergooding** [comment]
Resolved in https://github.com/microsoft/ClangSharp/pull/290
