### ISSUE TITLE
Better naming of anonymous types and fields

### ISSUE THREAD

**Issue by nathan-alden-sr** [microsoft/ClangSharp#137]
Implement an algorithm that can automatically determine the best applicable name for anonymous types and fields. During my mapping work, I have yet to run into an edge case with these. Some suggested rules:

- [ ] Anonymous fields should be named `Anonymous` as long as they are the only anonymous field in a type; otherwise, a number should be appended: `Anonymous1`, `Anonymous2`, etc.
- [ ] Anonymous types should automatically take the name of the field they are associated with if the field is named. For example, `_Range_e__Union` if the anonymous type is on a field named `Range`. The algorithm may also be able to handle multiple named fields (with different names) referencing the same anonymous type in certain circumstances.
- [ ] Unnamed anonymous types take the form `_Anonymous_e__Union`. Sometimes they conflict if multiple are defined within the same parent type. In these cases, a number should be appended: `_Anonymous_e__Union1`, `_Anonymous_e__Union2`, etc.

**Comment by tannergooding** [comment]
All of these should be getting handled now and should have test cases where applicable.
