### ISSUE TITLE
AccessViolation converting getDiagnosticSpelling result with getCString and ToString

### ISSUE THREAD

**Issue by tomevoll** [microsoft/ClangSharp#14]
try catch also dont prevent this crash.

[pastebin](http://pastebin.com/4Y1yYfZj)

**Comment by tannergooding** [comment]
Could you try to repro with the latest sources? I believe this is resolved now.

**Comment by tannergooding** [comment]
Closing this as we now have a number of tests that validate these various bits are working correctly.
