### ISSUE TITLE
Is there documentation?

### ISSUE THREAD

**Issue by PeterDraex** [microsoft/ClangSharp#144]
Hello,

is there any sort of documentation for ClangSharp? 

I'd like to genereate C# wrapper from [C/C++ header for Win32 API](https://github.com/microsoft/webauthn/blob/master/webauthn.h), can't find any tutorial on how to do that with ClangSharp.

Thanks.
Peter

**Comment by StephenHodgson** [comment]
If this is a Windows API, have you checked out https://github.com/microsoft/CsWinRT?

**Comment by PeterDraex** [comment]
@StephenHodgson It doesn't include headers that I need.

**Comment by StephenHodgson** [comment]
What's missing!

**Comment by PeterDraex** [comment]
@StephenHodgson 

This header is missing:
https://github.com/microsoft/webauthn/blob/master/webauthn.h

**Comment by tannergooding** [comment]
There isn't currently any documentation and it's something that should be worked on.

The simplest scenario is to get `ClangSharpPInvokeGenerator` and then pass in the appropriate args.
* There is an issue with native packages in a few cases so libClang and libClangSharp may need to be manually copied onto the path. https://github.com/microsoft/ClangSharp/issues/118 has more details

An example of possible command lines are: <https://github.com/microsoft/ClangSharp/blob/master/sources/ClangSharpPInvokeGenerator/Properties/launchSettings.json>, which is what is used to generate bindings for Clang and LLVM themselves.

I'll try to get something more comprehensive written up with examples, but I don't expect that will be completed today.

**Comment by Perksey** [comment]
Also if this is Win32 [TerraFX](https://github.com/terrafx/terrafx.interop.windows) might have what you need

**Comment by kkukshtel** [comment]
Bumping this again. Trying to figure out how to use this library as it seems like exactly what I need, but stunned there seems to be 0 documentation on how to use it, from an official Microsoft repo no less. Would love even just a basic sample of using it as part of both a project and the command line.

**Comment by tannergooding** [comment]
https://github.com/microsoft/ClangSharp/pull/214 adds some basic docs on how to use the P/Invoke generator. You can see https://github.com/microsoft/ClangSharp#generating-bindings for more details.

Please feel free to request additional information or clarification if its needed and I'll work on updating the docs further.
