### ISSUE TITLE
Pass all/some of command line paramaters as a json or xml file

### ISSUE THREAD

**Issue by jmaine** [microsoft/ClangSharp#148]
After attempting to run this, I noticed the list of '-t' and '-I' parameters to make it work is very large. Could have a system where we can define these paramaters in an xml or json file instead?

**Comment by tannergooding** [comment]
Parameters can be defined and passed via a response file, similarly to many other command line tools.

Essentially you define a text file that contains the parameters where there is one option/argument per line. The file typically has a `.rsp` extension, but this isn't required.
You then pass that into the binding generator as `ClangSharpPInvokeGenerator.exe @file.rsp`

You can see an example of this here: https://github.com/microsoft/ClangSharp/blob/master/sources/ClangSharpPInvokeGenerator/Properties/GenerateClang.rsp
and it being passed into the binding generator here: https://github.com/microsoft/ClangSharp/blob/master/sources/ClangSharpPInvokeGenerator/Properties/launchSettings.json#L5

You can also include response files from a response file: https://github.com/terrafx/terrafx.interop.windows/blob/main/generation/shared/dxgi/generate.rsp
which includes: https://github.com/terrafx/terrafx.interop.windows/blob/main/generation/remap.rsp and https://github.com/terrafx/terrafx.interop.windows/blob/main/generation/settings.rsp

**Comment by SamB** [comment]
Seems like this info should be in-tree somewhere.
