### ISSUE TITLE
Is there a way to BYO clang with version 9 and above?

### ISSUE THREAD

**Issue by dipidoo** [microsoft/ClangSharp#150]
Hi,

On macOS there seems to be an issue with the clang inside nuget dependency, I keep getting wrong type of cursor. This was not an issue with ClangSharp 8 when I use XCode's AppleClang. Is there a way I can do this with newer ClangSharp?

**Comment by tannergooding** [comment]
Could you provide some more details and the steps needed to reproduce the issue?

Clang frequently makes breaking changes each version and so the `libClang` loaded needs to match the version that `ClangSharp` is compiled for.

The current version of `ClangSharp` is currently target v10.0.0 of `libClang`: https://github.com/llvm/llvm-project/tree/llvmorg-10.0.0

**Comment by dipidoo** [comment]
Interesting. When used on MacOS, ClangSharp 8  works with AppleClang that is Clang 11 at the moment, perhaps this is working by accident? ClangSharp 10, on the other hand, will not work properly.

**Comment by tannergooding** [comment]
Perhaps there is a difference between AppleClang and the Clang10 binaries retrieved via https://releases.llvm.org/download.html for macOS.

The CI tests, which cover various things only exposed in v10, are all currently passing on macOS; and they consume the libClang binary from the NuGet package, which is the same as the official "Pre-Built Binaries" distributed by Clang/LLVM.

**Comment by dipidoo** [comment]
I reproed my issue on ClangSharp 8 by accidentally, instead of running ln -s as I usually do to libclang.dylib, copying it instead to the working directory. It seems to be triggered by not having a libclang.dylib dependency in the path. Anyhow, I realize this issue is too obscure to be actionable so I will close it for now and reopen if I can repro with more details.
