### ISSUE TITLE
libClangSharp throws exception

### ISSUE THREAD

**Issue by zebmason** [microsoft/ClangSharp#158]
var tu = ClangSharp.TranslationUnit.GetOrCreate(translationUnit);
throws Unable to cast object of type 'ClangSharp.Decl' to type 'ClangSharp.TranslationUnitDecl'
where translationUnit is output from a call to CXTranslationUnit.TryParse

To get this far I've had to include a copy of libClangSharp.dll sourced from an unzipped copy of libclangsharp.runtime.win-x86.10.0.0-beta1 downloaded from nuget.org which I've then copied the binary into the relevant build directory of a .NET Framework 4.7.2 project as I've not managed to build from source.

**Comment by zebmason** [comment]
I'll try and submit a unit test for this tomorrow. Probably find it works on CI...

**Comment by zebmason** [comment]
It does work on CI as the tests are there. So a difference between .NET standard and core. Looks like I need to implement TranslationUnitDecl.Create for some reason to avoid the cast failing

**Comment by zebmason** [comment]
Still don't know what is going awry and have separated out a test that passes in the code of this project:
```
        [Fact]
        public void ReadTest()
        {
            CXIndex _index = CXIndex.Create(false, false);
            string[] arr = { "-x", "c++" };
            var filePath = @"C:\Projects\BitBucket\deepstarts\DeepEndsTest\Source\Cpp\Cpp\SubStruct.cpp";
            var translationUnitError = CXTranslationUnit.TryParse(_index, filePath, arr, new CXUnsavedFile[] { },
                           CXTranslationUnit_Flags.CXTranslationUnit_None, out CXTranslationUnit translationUnit);
            var tu = TranslationUnit.GetOrCreate(translationUnit);
        }

        [Fact]
        public void ClassTemplatePartialSpecializationDeclTest()
```
whereas the `TranslationUnit.GetOrCreate` causes the crash in my code. Have built Debug x86 `ClangSharp.dll` and replaced my local copy with it to no effect.
Hence confused.

**Comment by tannergooding** [comment]
What version of libClang is being loaded/resolved?

**Comment by zebmason** [comment]
Tanner

Sorry trying to answer your question I created a batch file to run after build and copy over the binaries from various locations. This eventually resulted in me getting a working build but not being able to reproduce stepping into a debug DLL which I built from source myself. Ho hum.

Currently copying over
```
packages\ClangSharp.10.0.0-beta\lib\netstandard2.0\ClangSharp.dll
packages\libclang.10.0.0\content\x86\libclang.dll
packages\libclangsharp.runtime.win-x86.10.0.0-beta1\runtimes\win-x86\native\libClangSharp.dll
```

where `libclang.dll` has been downloaded from the LLVM website and is the version 10.0.0 build from 2020/03/25 09:14

Again apologies

**Comment by tannergooding** [comment]
Clang makes breaking changes nearly every major release and so you typically have to match versions exactly. They also include additional metadata in the types for different build configurations, and so you can't really use a debug version of libClang with a release version of libClangSharp.

The version of libClang and libClangSharp in the NuGet packages should match up with the respective ClangSharp build for your given platform. Unfortunately, NuGet doesn't seem to copy these dependencies to the output directory automatically if you don't do a RID specific build, which can lead to some weird failure cases. I have some more details on how to force RID specific builds here: https://github.com/microsoft/ClangSharp/issues/118#issuecomment-598305888 and am still trying to determine if there is a better long term solution.
