### ISSUE TITLE
Spiritous SEHException when debugging on linux

### ISSUE THREAD

**Issue by DCNick3** [microsoft/ClangSharp#167]
Running a program as simple as

```
using ClangSharp.Interop;
class Program
{
    static void Main(string[] args)
    {
        var index = CXIndex.Create();
    }
}
```

with debugger attached results in a `System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.` popping out in different places (depends on where do I put a breakpoint). If I put no breakpoint it shows up somewhere in standard library internals.

Program without a debugger runs just fine.

Does not seem to depend on ClangSharp version.

It is reproducible with both Rider and vs code debugger on arch linux and with rider remote debugging on debian.

I'm not really sure what causes this exception. It seems to have popped up on linux at dotnet/runtime#7091.

**Comment by rokups** [comment]
I am affected as well. What distro do you use? ArchLinux here.

**Comment by tannergooding** [comment]
What version of `libClang` do you have installed on your box?

The most common source of failures with ClangSharp are due to a mismatch between ClangSharp, libClangSharp, and libClang.
Clang frequently makes binary breaking changes between major versions and so the various components need to match versions exactly or various sporadic failures can occur.

**Comment by rokups** [comment]
Version 10.0.1 here. I suspected this may be some system incompatibility, hence i asked how to build runtimes package (#178). If i could test that we could have a good guess whether it is that or actually something else.

**Comment by rokups** [comment]
I tested with libClangSharp built on my system and result is exactly same. One thing i noticed is that it does not necessarily throw an exception on `CXIndex.Create();`. For example:

```cs
var compilation = CppParser.ParseFile($"/tmp/test.cpp",  options);    // <-- Calls CXIndex.Create() and CXTranslationUnit.Parse()
Console.WriteLine("Completed with errors: {0}", compilation.HasErrors);    // <-- breakpoint here
```

Putting a breakpoint on second line and allowing it to break there would throw `SEHException` at that location. Something else i noticed is that this issue happens in Rider IDE for me as well. I tested MonoDevelop and it does not produce any exceptions. It may be related to IDE.

**Comment by DCNick3** [comment]
> I am affected as well. What distro do you use? ArchLinux here.

Same, arch linux.

**Comment by DCNick3** [comment]
> Something else i noticed is that this issue happens in Rider IDE for me as well. I tested MonoDevelop and it does not produce any exceptions. It may be related to IDE.

Hmm, according to my research vscode and rider use different debugger backends (with some licensing muddle). It works for me in vscode and does not in Rider. What about monodevelop, which debugger backend does it use for dotnet core?

**Comment by DCNick3** [comment]
> I tested with libClangSharp built on my system and result is exactly same. One thing i noticed is that it does not necessarily throw an exception on `CXIndex.Create();`. For example:
> 
> ```cs
> var compilation = CppParser.ParseFile($"/tmp/test.cpp",  options);    // <-- Calls CXIndex.Create() and CXTranslationUnit.Parse()
> Console.WriteLine("Completed with errors: {0}", compilation.HasErrors);    // <-- breakpoint here
> ```
> 
> Putting a breakpoint on second line and allowing it to break there would throw `SEHException` at that location. Something else i noticed is that this issue happens in Rider IDE for me as well. I tested MonoDevelop and it does not produce any exceptions. It may be related to IDE.

Can confirm, building the helper library on my machine does not fix the issue, so binary compatibility is probably not a problem here.

**Comment by tannergooding** [comment]
Does the error occur if it is run without a debugger?

**Comment by rokups** [comment]
No, it runs just fine. Even if started from within IDE.

**Comment by tannergooding** [comment]
That does sound like a debugger specific issue then and I'm not sure if there is anything we can do to help resolve it.

I'd likely recommend logging an issue with the VSCode C# extension: https://github.com/OmniSharp/omnisharp-vscode
and with Rider: https://youtrack.jetbrains.com/issues/RIDER

I will see if I can get a repro in Ubuntu 20.04 later today (likely closer to the evening my time).

**Comment by DCNick3** [comment]
Rider issue: https://youtrack.jetbrains.com/issue/RIDER-51985

**Comment by tannergooding** [comment]
Closing as this is not currently actionable on the ClangSharp side.

**Comment by kekekeks** [comment]
Workaround: add `setenv("LIBCLANG_DISABLE_CRASH_RECOVERY", "1", 1);` to your `Program.Main`. It has to be `setenv` because [Environment.SetEnvironmentVariable is a fake and has no effect on objective reality whatsoever](https://github.com/dotnet/runtime/issues/9529).


```cs
[DllImport("libc")]
static extern void setenv(string name, string value, int overwrite);

static unsafe void Main(string[] args)
{
    if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
        setenv("LIBCLANG_DISABLE_CRASH_RECOVERY", "1", 1);
```

Alternatively just set LIBCLANG_DISABLE_CRASH_RECOVERY=1 before starting your app.
