### ISSUE TITLE
www.clangsharp.org reports Azure 404

### ISSUE THREAD

**Issue by kdriedger-simutech** [Microsoft/ClangSharp#17]
Seems that going to clangsharp.org has some configuration problem in Azure.

Is this project still active?

================ Text from clangsharp.org ===============

Error 404 - Web app not found.

The web app you have attempted to reach is not available in this Microsoft Azure App Service region. This could be due to one of several reasons:

1. The web app owner has registered a custom domain to point to the Microsoft Azure App Service, but has not yet configured Azure to recognize it. Click here to read more.

2. The web app owner has moved the web app to a different region, but the DNS cache is still directing to the old IP Address that was used in the previous region. Click here to read more.

**Comment by mjsabby** [comment]
yup, project is still active and the azure website I'm working on it.

**Comment by mjsabby** [comment]
Redirects to the Github page now.
