### ISSUE TITLE
Struct definition with the word struct in it generates invalid C# code

### ISSUE THREAD

**Issue by mjsabby** [microsoft/ClangSharp#173]
```c
struct a {
	struct a *next;
	struct a *prev;
};
```
produces

```csharp
    public unsafe partial struct a
    {
        [NativeTypeName("struct a*")]
        public struct a* next;

        [NativeTypeName("struct a*")]
        public struct a* prev;
    }
```

**Comment by mjsabby** [comment]
@tannergooding any suggestions on this one?

**Comment by tannergooding** [comment]
This looks to be specific to processing in C mode. It works as expected for C++ mode.

It looks like in both cases it is a Pointer where the PointeeType is an ElaboratedType and the NamedType is then a TagType.
However, for C++ the `TagType` has a name of `a` while in C it is `struct a` and so there would need to be a check that strips the `struct ` or `enum ` prefix from it in this case: https://github.com/microsoft/ClangSharp/blob/master/sources/ClangSharp.PInvokeGenerator/PInvokeGenerator.cs#L1305
