### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by WebFreak001** [microsoft/ClangSharp#177]
There have been a lot of useful improvements in libClangSharp which I currently cannot use via nuget as the 10.0.0-beta was released 2020-04-22. It would be nice if a new ClangSharp version could be released soon.

Currently for the functionality I need I need to manually import like so which I find quite error-prone but helps me achieve my goal:
```cs
// not yet available in ClangSharp 10.0.0-beta, but already in libClangSharp 10.0.2-beta2
// would be Cursor.HasExternalStorage or clangsharp.Cursor_getHasExternalStorage
[DllImport("libClangSharp", CallingConvention = CallingConvention.Cdecl, EntryPoint = "clangsharp_Cursor_getHasExternalStorage", ExactSpelling = true)]
public static extern uint Cursor_getHasExternalStorage(CXCursor C);
```

**Comment by tannergooding** [comment]
This should be resolved now. There exists an 11.0.0-beta2 version of ClangSharp and the P/Invoke Generator that works with the 11.0.0-beta1 version of libClangSharp.

A new 11.0.0-beta2 version of libClangSharp has also been published which will work with https://github.com/microsoft/ClangSharp/pull/213. An updated version of ClangSharp will likely be published after some additional fixes/work goes in.
