### ISSUE TITLE
Any plans to take the PInvokeGenerator to the next level?

### ISSUE THREAD

**Issue by NickStrupat** [microsoft/ClangSharp#183]
It would be very cool if this tool leveraged `vcpkg` to automatically generate .NET Core PInvoke bindings and the NuGet packages for all the (trivially supported) C/C++ packages in `vcpkg`.

Has this idea been discussed?

**Comment by tannergooding** [comment]
It has not been discussed yet.

While ClangSharp is constantly getting better at handling scenarios, there are still a lot of concepts that don't cleanly translate to .NET and where they may require explicit fixups, remapping additions, or options passed in to ensure the traversal works.

Users are always free to create and maintain their own bindings as appropriate 😄.
