### ISSUE TITLE
CXCursor.LambdaContextDecl cause AccessViolationException

### ISSUE THREAD

**Issue by phizch** [microsoft/ClangSharp#184]
### Cause: 

An assert raised in libClang.
see:
https://github.com/llvm/llvm-project/blob/ef4ffcafbb2deeb30ccc30ebcdf9a5a843a27ec1/clang/lib/AST/DeclCXX.cpp#L1534-L1538

If `CXXRecordDecl::isLambda()` is false an assert is caused, which somehow writes to invalid memory.

### Solution:

Check `CXXRecordDecl::isLambda()` before accessing `CXXRecordDecl::getLambdaContextDecl()`

```cpp
 CXCursor clangsharp_Cursor_getLambdaContextDecl(CXCursor C) { 
     if (clang_isDeclaration(C.kind)) { 
         const Decl* D = getCursorDecl(C); 
  
         if (const CXXRecordDecl* CRD = dyn_cast<CXXRecordDecl>(D)) { 
            if( CRD->isLambda() )
                return MakeCXCursor(CRD->getLambdaContextDecl(), getCursorTU(C));
         } 
     } 
  
     return clang_getNullCursor(); 
 } 
```

I've implemented the change and it fixed the problem.

### Source location:

https://github.com/microsoft/ClangSharp/blob/2e4f410e6c065a2e51b54889f202b61c3c4a5438/sources/libClangSharp/ClangSharp.cpp#L1690-L1700

**Comment by tannergooding** [comment]
This was resolved in #185
