### ISSUE TITLE
Get pre-processed file

### ISSUE THREAD

**Issue by HFFernandes** [microsoft/ClangSharp#20]
On the command line, **clang -E test.cpp** will show you the preprocessed output.

```
> # 1 "prog.c"
> # 1 "<built-in>" 1
> # 1 "<built-in>" 3
> # 157 "<built-in>" 3
> # 1 "<command line>" 1
> # 1 "<built-in>" 2
> # 1 "prog.c" 2
> int main (void)
> {
> int a;
> }
```

Is there a way to get pre-processed with ClangSharp?

**Comment by tannergooding** [comment]
Not currently, but it wouldn't be hard to configure by extending the CursorWriter class in the P/Invoke Binding Generator.

**Comment by HFFernandes** [comment]
Thanks.
