### ISSUE TITLE
test-win32metadata failing

### ISSUE THREAD

**Issue by tannergooding** [microsoft/ClangSharp#209]
The `test-win32metadata` leg is failing with no changes made on the ClangSharp side:
```
D:\a\1\s\artifacts\win32metadata\generation\emitter\obj\generated\WinRT.modified.cs(3398,17): error CS0101: The namespace 'Windows.Win32.WinRT' already contains a definition for 'RoErrorReportingFlags'
D:\a\1\s\artifacts\win32metadata\generation\emitter\obj\generated\Dhcp.modified.cs(1268,210): error CS0246: The type or namespace name '__AnonymousRecord_dhcpsapi_L1229_C5' could not be found (are you missing a using directive or an assembly reference?)
D:\a\1\s\artifacts\win32metadata\generation\emitter\obj\generated\Dhcp.modified.cs(1282,210): error CS0246: The type or namespace name '__AnonymousRecord_dhcpsapi_L1243_C5' could not be found (are you missing a using directive or an assembly reference?)
D:\a\1\s\artifacts\win32metadata\generation\emitter\obj\generated\Dhcp.modified.cs(1297,210): error CS0246: The type or namespace name '__AnonymousRecord_dhcpsapi_L1260_C5' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by tannergooding** [comment]
CC. @sotteson1, was there a change made to the win32metadata fork of ClangSharp that needs to be backported?

**Comment by sotteson1** [comment]
I thought master had everything I needed but I'll take a look. I might have missed something.

**Comment by sotteson1** [comment]
I found the fix for the problem and I submitted a PR for it. If I had tried to get win32metadata to use the nuget package I would have hit this right away! Next time it updates with this change I'll work on that.

**Comment by sotteson1** [comment]
Oh, although the first error is something different. In my rsp I had been excluding that enum like this:

--exclude
Windows::Foundation::Diagnostics::RoErrorReportingFlags
ABI::Windows::Foundation::Diagnostics::RoErrorReportingFlags

But to fix this problem I had to do this:
--exclude
RoErrorReportingFlags

I'm not sure what's different that causes this with the latest ClangSharp changes. I must not have had them in my copy.

**Comment by tannergooding** [comment]
> But to fix this new problem I had to do this:

That doesn't seem right. I'll take a look

**Comment by tannergooding** [comment]
@sotteson1, this will be resolved with https://github.com/microsoft/ClangSharp/pull/219.

The logic for generating the qualified name was changed to use `.` instead of `::`. #219 updates things so that either works for remapping
