### ISSUE TITLE
libclang alternative names

### ISSUE THREAD

**Issue by benpye** [microsoft/ClangSharp#22]
On at least Ubuntu the dynamic library is called `libclang-x.x.so` rather than just `libclang.so`, this means a symlink currently needs to be created so that the `DllImport` may find the shared library. Ideally there would be some other solution for this, this matters more for .NET Core where there is no concept of a `DllMap` as on Mono. Maybe https://github.com/dotnet/corefx/pull/27258 and the corresponding CoreCLR work may provide a solution in .NET Core 2.2 or above, however perhaps some other solution could be found before then.

**Comment by mjsabby** [comment]
@benpye I wrote a tool (https://github.com/mjsabby/PInvokeCompiler) that basically converts the PInvoke Decls and turns them into lower-level boilerplate so the user can supply the library.

ClangSharp needs to go the same way LLVMSharp does here, I just haven't had the time yet.

There is also a version of the C# Compiler here, https://www.nuget.org/packages/CSCWithCompilerIntrinsics that can help.

Now that we'll be on NS 2.0 thanks to your work, we should be able to include that nuget package on all platforms and generate a package that has the ability to specify a custom so/dll path.

**Comment by tannergooding** [comment]
@mjsabby, what do you think about using your above library vs suggesting users target `netcoreapp3.0` and utilize the built-in `NativeLibrary.SetDllImportResolver` function?

**Comment by mjsabby** [comment]
@tannergooding What I'm trying to convey in my comment is that I'd love to expose a method called

`LoadLibClang(…);`

so that users can provide their own libclang. In netcoreapp3.0+ we can use NativeLibrary.* and maybe on pre-3.0 we can roll our own in Clangsharp? Or we could say as you're saying ... upgrade to 3.0 to get the benefit of being able to provide your own libclang.

**Comment by tannergooding** [comment]
> Or we could say as you're saying ... upgrade to 3.0 to get the benefit of being able to provide your own libclang.

My point is that ClangSharp doesn't need to do anything and can continue targeting netstandard20.

Consumers of the library can independently target netcoreapp3.0 and take advantage of `NativeLibrary.SetDllImportResolver` to resolve `libclang` as appropriate (it is a separate hook that consumers can utilize for resolving a library, independently of updating the library exposing the `DllImport`s).

> maybe on pre-3.0 we can roll our own in Clangsharp

Yes, this is possible as well. The trouble ends up being the additional overhead of setting this all up (although most of it can probably be supported via the PInvokeGenerator, so maybe it won't be too bad).

Namely, doing this for pre-3.0 will involve changing every `DllImport` to a `delegate` with the appropriate `UnmanagedFunctionPointer` attribute. It will then involve a static readonly per delegate of the form `public static readonly _createIndex createIndex = GetExport<_createIndex>("clang_createIndex");`.

`GetExport` will need to handle the pre-3.0 and post-3.0 differences (using `NativeLibrary` or using its own loader logic that simulates what the existing JIT calls do) and will need to also perform the appropriate checks for loading the library if it hasn't been already (basically, `if (libclangHandle == IntPtr.Zero) { libclangHandle = LoadLibrary("libclang"); }`, although threading might also be a concern here)

**Comment by tannergooding** [comment]
There now exists a `DllImportResolver` which looks for the most common variants and is also hookable so users can add their own names as well
