### ISSUE TITLE
Switching language to C does not change language standard

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/ClangSharp#220]
Trying to parse a file as C just by using `-x c` results in the following error

```
  error: invalid argument '--std=c++17' not allowed with 'C'
```

ClangSharp should be smart enough to switch std to c17 when the language is switched to C.

**Comment by tannergooding** [comment]
This is probably a disconnect here: https://github.com/microsoft/ClangSharp/blob/main/sources/ClangSharpPInvokeGenerator/Program.cs#L438-L439
It's probably ending up as -x c --std c++17 and clang treats that as C++17
