### ISSUE TITLE
Run build.bat return System.BadImageFormatException 

### ISSUE THREAD

**Issue by ArionTT** [microsoft/ClangSharp#23]
My llvm and clang is cloned from Github mirror repo. 
I built the Debug version llvm and clang.
![image](https://user-images.githubusercontent.com/21036443/39911427-ef2dc894-552d-11e8-9728-e40a8686aeb5.png)

run build.bat result
![image](https://user-images.githubusercontent.com/21036443/39911476-17dad818-552e-11e8-86a5-f85ba55f65fd.png)

What`s wrong with it?

**Comment by tannergooding** [comment]
@ArionTT, I imagine there was a mismatch between the `libclang` library being loaded and what `ClangSharp` was expecting.

The repo has undergone a significant rewrite and now has CI validation that both 32-bit and 64-bit Windows are working as expected. It would be good if you could retry and see if this issue still reproduces.

**Comment by tannergooding** [comment]
Closing as there has been no further update. Please feel free to reopen if you can still reproduce the issue.
