### ISSUE TITLE
Missing 'libClangSharp.so' for linux-x64 platform

### ISSUE THREAD

**Issue by abonSerg** [microsoft/ClangSharp#230]
I have a problem with running ClangSharp in docker because libClangSharp.so library is missing for  linux-x64. Is there a nuget for this platform?

**Comment by tannergooding** [comment]
There is not and cannot be a generic `linux-x64` package as `libClang.so` itself is built for (and designed around) per distro binaries.

If Clang itself starts producing generic linux binaries, then `libClangSharp` will be able to as well.
