### ISSUE TITLE
Missing NativeTypeNameAttribute

### ISSUE THREAD

**Issue by talanc** [microsoft/ClangSharp#231]
I'm getting a 'NativeTypeName could not be found' error after generating:

`        [DllImport("SketchUpAPI", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void SUGetAPIVersion([NativeTypeName("size_t *")] nuint* major, [NativeTypeName("size_t *")] nuint* minor);`

Should I just create a NativeTypeNameAttribute class?

**Comment by tannergooding** [comment]
Yes, you can manually define an attribute such as: <https://github.com/microsoft/ClangSharp/blob/main/sources/ClangSharp/Internals/NativeTypeNameAttribute.cs>

Happy to take a PR that automatically creates this file as well 😄

**Comment by tannergooding** [comment]
https://github.com/microsoft/ClangSharp/pull/284 adds support for this via `--config generate-helper-types`.
