### ISSUE TITLE
Consideration to offer ClangSharpPInvokeGenerator as .NET Core global tools

### ISSUE THREAD

**Issue by dotChris90** [microsoft/ClangSharp#24]
Hello Clang-Team, 

hope you still looking into this repo :D 

In my opinion it would be a nice idea to offer your very interesting ClangSharpPInvokeGenerator as a .NET Core global tool. 

People using .NET Core simple can download it from NuGet and do sth like dotnet pinvoke ./myNativeCode . Finish. 

I am not sure if you think the same way but just wanted to let you know ;) 

Greetings

**Comment by tannergooding** [comment]
Going to close this in favor of https://github.com/microsoft/ClangSharp/issues/46 (which tracks the same thing).

I'm going to get https://github.com/microsoft/ClangSharp/pull/72 and a follow-up PR merged and then I plan on getting new preview packages published, which includes `ClangSharpPInvokeGenerator` as a global tool.
