### ISSUE TITLE
Structure fields with char* or char[x] do not get translated to string

### ISSUE THREAD

**Issue by Timo-Weike** [microsoft/ClangSharp#250]
If I have a structure like
~~~ c
typedef struct {
	char* something;
	char something[20];
} Test1;
~~~
I would expect it to convert to something like
~~~ cs
public unsafe partial struct Test1
{
    [NativeTypeName("char *")]
    [MarshalAs(UnmanagedType.LPStr)]
    public string something;

    [NativeTypeName("char [20]")]
    [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 20 + 1)]
    public string something;
}
~~~
but with `--std=c11` I instead get
~~~ cs
public unsafe partial struct Test1
{
    [NativeTypeName("char *")]
    public sbyte* something;

    [NativeTypeName("char [20]")]
    public fixed sbyte something[20];
}
~~~

**Comment by AronRubin** [comment]
I would like to upvote this issue.

**Comment by tannergooding** [comment]
This is expected. There is no way to know that given C code represents a null terminated string. It could equally be a ASCII string, a pointer to a single byte, a pointer to a size associated buffer, a pointer to a fixed length buffer, a byte buffer, or some other metadata.

ClangSharp generates blittable bindings to ensure there is no functionality lost and that it is 1-to-1 (or as close as possible) with the corresponding C/C++ code.
