### ISSUE TITLE
Enums cause the tool to create invlaid C# code

### ISSUE THREAD

**Issue by Timo-Weike** [microsoft/ClangSharp#251]
If I have the c types
~~~ c
typedef enum myEnum {
	One,
	Two
} enum_t;

typedef struct {
	enum_t enumField;
} Test1;
~~~
the tool generates C# code like
~~~ cs
public enum myEnum
{
	One,
	Two,
}

public partial struct Test1
{
	[NativeTypeName("enum_t")]
	public enum myEnum enumField;
}
~~~
which is incorrect. 

In contrast, if I drop the `myEnum` from the `typedef` the tool generates the correct C# code. 

PS: It is the same for `typedef struct name { ... } otherName;`

**Comment by tannergooding** [comment]
This was resolved with https://github.com/microsoft/ClangSharp/pull/256
