### ISSUE TITLE
Inconsistent behavior of ClangSharpPInvokeGenerator

### ISSUE THREAD

**Issue by MangoTwo2** [microsoft/ClangSharp#26]
Using a simple C++ class header we get different results running the generator (we use clang 6.0, but also tested with 6.01):

`C:\temp\ClangSharp\ClangSharpPInvokeGenerator\bin\Debug\netcoreapp2.0    master±  dotnet ClangSharpPInvokeGenerator.dll  --f decoder.h  --output decoder.cs --libraryPath x --namespace Decoder
libclang: crash detected during parsing: {
  'source_filename' : 'decoder.h'
  'command_line_args' : ['clang', '-x', 'c++', '
C:\temp\ClangSharp\ClangSharpPInvokeGenerator\bin\Debug\netcoreapp2.0    master±  dotnet ClangSharpPInvokeGenerator.dll  --f decoder.h  --output decoder.cs --libraryPath x --namespace Decoder
Error: CXError_ASTReadError

C:\temp\ClangSharp\ClangSharpPInvokeGenerator\bin\Debug\netcoreapp2.0    master±  dotnet ClangSharpPInvokeGenerator.dll  --f decoder.h  --output decoder.cs --libraryPath x --namespace Decoder
Error: CXError_ASTReadError

C:\temp\ClangSharp\ClangSharpPInvokeGenerator\bin\Debug\netcoreapp2.0    master±  dotnet ClangSharpPInvokeGenerator.dll  --f decoder.h  --output decoder.cs --libraryPath x --namespace Decoder
libclang: crash detected during parsing: {
  'source_filename' : 'decoder.h'
  'command_line_args' : ['clang', '-x', 'c++', '
C:\temp\ClangSharp\ClangSharpPInvokeGenerator\bin\Debug\netcoreapp2.0    master±  dotnet ClangSharpPInvokeGenerator.dll  --f decoder.h  --output decoder.cs --libraryPath x --namespace Decoder

C:\temp\ClangSharp\ClangSharpPInvokeGenerator\bin\Debug\netcoreapp2.0    master±  dotnet ClangSharpPInvokeGenerator.dll  --f decoder.h  --output decoder.cs --libraryPath x --namespace Decoder

C:\temp\ClangSharp\ClangSharpPInvokeGenerator\bin\Debug\netcoreapp2.0    master±  dotnet ClangSharpPInvokeGenerator.dll  --f decoder.h  --output decoder.cs --libraryPath x --namespace Decoder
libclang: crash detected during parsing: {
  'source_filename' : 'decoder.h'
  'command_line_args' : ['clang', '-x', 'c++', '
C:\temp\ClangSharp\ClangSharpPInvokeGenerator\bin\Debug\netcoreapp2.0    master±  dotnet ClangSharpPInvokeGenerator.dll  --f decoder.h  --output decoder.cs --libraryPath x --namespace Decoder

C:\temp\ClangSharp\ClangSharpPInvokeGenerator\bin\Debug\netcoreapp2.0    master±  dotnet ClangSharpPInvokeGenerator.dll  --f decoder.h  --output decoder.cs --libraryPath x --namespace Decoder

C:\temp\ClangSharp\ClangSharpPInvokeGenerator\bin\Debug\netcoreapp2.0    master±  dotnet ClangSharpPInvokeGenerator.dll  --f decoder.h  --output decoder.cs --libraryPath x --namespace Decoder

C:\temp\ClangSharp\ClangSharpPInvokeGenerator\bin\Debug\netcoreapp2.0    master±  dotnet ClangSharpPInvokeGenerator.dll  --f decoder.h  --output decoder.cs --libraryPath x --namespace Decoder
libclang: crash detected during parsing: {
  'source_filename' : 'decoder.h'
  'command_line_args' : ['clang', '-x', 'c++', '`

**Comment by tannergooding** [comment]
@MangoTwo2, could you try this again on the latest sources.

The repo has undergone a significant rewrite and it would be good to know if you are still hitting this issue.

**Comment by tannergooding** [comment]
Closing as there has been no further update. Please feel free to reopen if you can still reproduce the issue.
