### ISSUE TITLE
Consider allowing the generator to split the types into one file per type

### ISSUE THREAD

**Issue by tannergooding** [microsoft/ClangSharp#30]
Currently the generator spits out the source files at a granularity of one cs file per input.

It would be beneficial in some scenarios if the user could specify that instead these should be spit out at one cs file per "type" in the input.

**Comment by tannergooding** [comment]
I'm willing to do the work here, if you feel it is something worth taking.

**Comment by mjsabby** [comment]
Yup, sounds good.
