### ISSUE TITLE
DLL not found 

### ISSUE THREAD

**Issue by norbert-p** [Microsoft/ClangSharp#35]
After adding ClangSharp to my project and writing some code, when I run the code I get a DLLNotFound exception at the first call to one of the clang object's static methods.

I need to get the clang.dll from somewhere and copy it manually to my bin/Debug folder, then my code works. 

What is the intended way of working? Am I missing a dependency?

This is Win 10 / VS 2017 / .NET FW 4.5 / Web application template.

Thanks for any hints!

norbert-p

**Comment by tannergooding** [comment]
It should normally just work if you have LLVM installed and selected the option to add it to your path. Otherwise, you need to have a copy exist somewhere that the application can find it.

**Comment by norbert-p** [comment]
Thanks for your fast reply. I did not realize that clangsharp presupposes an installation.
