### ISSUE TITLE
Setup a CI system for ClangSharp

### ISSUE THREAD

**Issue by tannergooding** [microsoft/ClangSharp#36]
As per https://github.com/Microsoft/ClangSharp/pull/34#issuecomment-486877211, it would be nice if ClangSharp could be connected to Azure DevOps for CI and other build infrastructure niceties.

It may be possible to utilize `dotnet/arcade` for this, or to setup a smaller localized infrastructure.

**Comment by EgorBo** [comment]
+ for up-to-date nuget packages 🙂

**Comment by tannergooding** [comment]
I put up a PR which sets up most of the infrastructure required: https://github.com/microsoft/ClangSharp/pull/60

The only thing really missing is an AzDO project so I can configure the `azure-pipelines.yml`

**Comment by tannergooding** [comment]
This is largely resolved now. It would still be nice to get signing support setup and to get new nuget packages for `ClangSharp` proper uploaded.
