### ISSUE TITLE
-include parameter does not seem to work

### ISSUE THREAD

**Issue by norbert-p** [microsoft/ClangSharp#39]
I am using -include as command line parameter to get some type definitions that are presupposed by a header file that I need to parse and analyse. This works fine when I call clang directly from the command shell, but seems to fail  when I call parseTranslationUnit2() via CLangSharp.

I have attached a little demo application where datatypes.h has the typedef u8 which is implicitly required from DataDictionary.h, the file that should be analysed. In the example all u8 based type declarations are resolved to int, so I suppose that the -include command line option is somehow not working. 

Any ideas about this?
[ConsoleApp1.zip](https://github.com/Microsoft/ClangSharp/files/3126399/ConsoleApp1.zip)

**Comment by tannergooding** [comment]
Could you try to repro with the latest sources? I just did a fairly large rewrite of the code and it may work as expected with the latest sources.

**Comment by norbert-p** [comment]
Thanks for your reply tannergooding. By now I have cloned the latest source from here, I have removed the nuget dependency, and have instead referenced the ClangSharp source code projects.

The results are still identical. Do you think you can help any further?

**Comment by tannergooding** [comment]
Sorry for the late response, I missed your last reply.

`clang.parseTranslationUnit2` takes command line arguments for `clang` (https://clang.llvm.org/docs/ClangCommandLineReference.html). `clang` expects you to use `-I<dir>`, `--include-direction <arg>`, or `--include-directory=<arg>`
