### ISSUE TITLE
Clarify clang version/building instructions

### ISSUE THREAD

**Issue by xoofx** [microsoft/ClangSharp#48]
Hey,

It's difficult from the codebase to know which Clang version is currently bound to the generated codegen.

I assume that the current version is 8.0.0? (as per PR #28) 

Could we add this information to the readme.md? (along some prerequisites - what to install to get ClangSharp generator working...etc)

If you are ok with that, I can send a PR?

Side question: how do you see the packaging automated (even locally)? Do we want to put the relevant libclang DLLs for all platforms in an ext  in LFS on github and grab them automatically in the runtime/ csproj? - with the small target file along the nuget package to make it compatible with both .NET framework and .NET CoreApp? (I can send a PR for that if you want as well)

**Comment by mjsabby** [comment]
PR for the first one makes sense, the second one is less clear if we want libclang in the repo. Although with LFS the concerns are purely principle based as opposed to putting a binary a git repo.

**Comment by xoofx** [comment]
> the second one is less clear if we want libclang in the repo. Although with LFS the concerns are purely principle based as opposed to putting a binary a git repo.

What do you have in mind?

One problem I see is that `libclang.dll` on Windows x86/x64 is only distributed via an exe installer, which makes packaging automation difficult. The other platforms provide big compressed files that needs to be unpack...etc.

Another problem is to package all libclang in ClangSharp as it would make the package horribly big and maybe not working with NuGet that restrict package sizes. I don't know how runtime dependent packages are working actually (e.g `runtime.ubuntu.14.04-x64.libclang` )... have you been trying that? (for libLLVM I can see that there are packages that look like RID dependent)

I would like to release a package on top of ClangSharp but I'm being a bit blocked to not being able to use the latest 8.0.0... I would like to avoid to internalize ClangSharp in my project and ship my own libclang on the side...

**Comment by tannergooding** [comment]
I agree, the first one should just be a PR. With the infrastructure update that just went in, a `Contributing.md` that also details how to build/restore/test/pack/etc could also be included.

For the latter, we should likely just have the appropriate nuget package setup and pull it in as a dependency.

**Comment by xoofx** [comment]
> For the latter, we should likely just have the appropriate nuget package setup and pull it in as a dependency.

Yeah, I had to proceed with https://github.com/xoofx/libclang and made an internal copy of ClangSharp into [CppAst](https://github.com/xoofx/CppAst)
