### ISSUE TITLE
Explicitly set C# version

### ISSUE THREAD

**Issue by sandervrijders** [microsoft/ClangSharp#59]
After cloning the repo and opening it in Visual Studio 2017, IntelliSense complains about missing language features. This is since by default the last major version of C# is used (7.0) and certain features are 7.1+ (such as async Main). I suggest setting the LangVersion in the csproj files to latest:

```
<LangVersion>latest</LangVersion>
```

**Comment by mjsabby** [comment]
Feel free to send a PR. You can use Directory.Build.props and set `LangVersion` there.

**Comment by tannergooding** [comment]
I put up a PR that does this and configures infrastructure for the repo in general: https://github.com/microsoft/ClangSharp/pull/60

**Comment by tannergooding** [comment]
Should be resolved now.
