### ISSUE TITLE
broken link in README.md: A great example of ClangSharp's use case is its self-hosting mechanism Clang Sharp PInvoke Generator

### ISSUE THREAD

**Issue by ghuntley** [microsoft/ClangSharp#66]
Not 100% sure where this should link to, otherwise would have sent in a PR.

**Comment by tannergooding** [comment]
It should likely link to https://github.com/microsoft/ClangSharp/tree/master/sources/ClangSharpPInvokeGenerator now.

Although that is really just the exe frontend now and the bulk logic is in https://github.com/microsoft/ClangSharp/tree/master/sources/ClangSharp.PInvokeGenerator

**Comment by tannergooding** [comment]
This has been resolved with https://github.com/microsoft/ClangSharp/pull/71
