### ISSUE TITLE
Access Violation with Code Completion

### ISSUE THREAD

**Issue by JinShil** [Microsoft/ClangSharp#7]
I'm trying to use the code completion features of this library.  Here's a simple example:

``` C#
// input is the text of my C++ source file
public static void DoCodeCompletion(string input, int row, int column)
{
    List<Completion> completions = new List<Completion>();

    string fileName = Path.GetTempFileName();
    File.WriteAllText(fileName, input);

    CXIndex index = clang.createIndex(1, 0);
    CXUnsavedFile unsavedFile;
    CXTranslationUnit tu;
    string[] arr = { "-x", "c++" };
    CXErrorCode errorCode = clang.parseTranslationUnit2(index, fileName, arr, 2, out unsavedFile, 0, (uint)CXTranslationUnit_Flags.CXTranslationUnit_PrecompiledPreamble, out tu);
    // errorCode is CXError_Success

    IntPtr pResults = clang.codeCompleteAt(tu, fileName, (uint)row, (uint)column, out unsavedFile, 0, 0);
    CXCodeCompleteResults results = Marshal.PtrToStructure<CXCodeCompleteResults>(pResults);

    // Access violation here
    clang.disposeCodeCompleteResults(out results);
    clang.disposeTranslationUnit(tu);

    File.Delete(fileName);
}
```

``` C++
struct Adder
{
    int add(int a, int b)
    {
        return a + b;   
    }
};

void fn()
{

}

int main()
{
    Adder adder;
    adder.      <--  Initiating completion here

    return 0;
}
```

It results in an access violation at `disposeCodeCompleteResults`.  

Please advise.  
Thanks!

**Comment by mjsabby** [comment]
Thanks for reporting this, I can reproduce this. I have a debug build of Clang that I'll look into over the weekend.

**Comment by gudaol** [comment]
Hello!
Any news on this issue?

**Comment by mjsabby** [comment]
Sorry this slipped my radar.

Can you add the following to your code:

[DllImport("libclang.dll", EntryPoint = "clang_disposeCodeCompleteResults", CallingConvention = CallingConvention.Cdecl)]
    public static extern void disposeCodeCompleteResultsTryingOut(IntPtr Results);

Then pass in 

    IntPtr pResults = clang.codeCompleteAt(tu, fileName, (uint)row, (uint)column, out unsavedFile, 0, 0);

pResults.

I think that is the problem. If you can confirm, great, otherwise I will try it out.

**Comment by JinShil** [comment]
Sorry, I had to move on to a C++/CLI implementation.  I don't have the setup for testing anymore.

**Comment by gudaol** [comment]
I can confirm, this solves the problem.

**Comment by mjsabby** [comment]
Alright, next release that's coming out for Clang 3.7 will have this fixed.
