### ISSUE TITLE
CXString.ToString() in Extensions.cs

### ISSUE THREAD

**Issue by gudaol** [Microsoft/ClangSharp#9]
Hello,

this
public partial struct CXString
    {
        public override string ToString()
        {
            string retval = Marshal.PtrToStringAnsi(this.data);
            clang.disposeString(this);
            return retval;
        }
    }

should look like this:
public partial struct CXString
    {
        public override string ToString()
        {
            string retval = Marshal.PtrToStringAnsi(clang.getCString (this));
            clang.disposeString(this);
            return retval;
        }
    }

Took me a day to figure out, why i was getting USRs like this "ߌي" or nulls. :D

**Comment by mjsabby** [comment]
Thanks for bug report and proposed fix. I'll gladly take a pull-request! Or I can fix it in a day or two.

**Comment by tannergooding** [comment]
I believe this should be fixed now. However, it's worth noting the disposing the CXString is an explicit action on the end-users part now, since you may get the same underlying CString returned for a handle multiple times.
